OR={
'PhpTravels_Url':"https://www.phptravels.net/",
'Home_page_Logo':"//div[@class='header-logo go-right']//a//img",
'Home_Tab_Link':"//a[contains(text(),'Home')]",
'Blog_Tab_Link':"//a[contains(text(),'Blog')]",
'Offers_Tab_Link':"//a[contains(text(),'Offers')]",
'Company_Tab_Dorpdown':"//a[contains(text(),'Company')]",
'About_Us_Link':"//a[contains(text(),'About us')]",
'Contact_Us_Link':"//a[contains(text(),'Contact Us')]",
'Terms_Conditions_Link':"//a[contains(text(),'Terms and Conditions')]",
'Privacy_Policy_Link':"//li[@class='text-center']//ul//li//a[contains(text(),'Privacy Policy')]",
'My_Account_Dropdown':"//div[@class='dropdown dropdown-login dropdown-tab']//a[@id='dropdownCurrency']",
'Login_Link':"//a[@class='dropdown-item active tr']",
'Sign_Up_Link':"//a[@class='dropdown-item tr']",
'Currency_Dropdown':"//a[@class='dropdown-item tr']",
'Indian_Currency':"//a[contains(text(),'INR')]",
'Japaneese_Currency':"//a[contains(text(),'JPY')]",
'SAR_Currency':"//a[contains(text(),'SAR')]",
'GBP_Currency':"//a[contains(text(),'GBP')]",
'EUR_Currency':"//a[contains(text(),'EUR')]",
'PKR_Currency':"//a[contains(text(),'PKR')]",
'KWD_Currency':"//a[contains(text(),'KWD')]",
'USD_Currency':"//a[@class='dropdown-item text-center'][contains(text(),'USD')]",
'CNY_Currency':"//a[contains(text(),'CNY')]",
'TRY_Currency':"//a[contains(text(),'TRY')]",
'RUB_Currency':"//a[contains(text(),'RUB')]",
'Language_Dropdown':"//a[@id='dropdownLangauge']",
'Russian_Language':"//a[@id='ru']",
'Farsi_Language':"//a[@id='fa']",
'German_Language':"//a[@id='de']",
'Vietnamese_Language':"//a[@id='vi']",
'French_Language':"//a[@id='fr']",
'Turkish_Language':"//a[@id='tr']",
'Arabic_Language':"//a[@id='ar']",
'Spanish_Language':"//a[@id='es']",
'English_Languge':"//a[@id='en']",
'Hotels_Link':"//a[@class='text-center hotels active']",
'Destination_Text':"//div[@id='select2-drop']//input[@class='select2-input']",
'Check_In_Date':"//input[@id='checkin']",
'Check_Out_Date':"//input[@id='checkout']",
'Adults_Add_Button':"//div[contains(@class,'col o2')]//button[contains(@class,'btn btn-white bootstrap-touchspin-up')][contains(text(),'+')]",
'Adults_Remove_Button':"//div[contains(@class,'col o2')]//button[contains(@class,'btn btn-white bootstrap-touchspin-down')][contains(text(),'-')]",
'Childs_Add_Button':"//div[contains(@class,'col 01')]//button[contains(@class,'btn btn-white bootstrap-touchspin-up')][contains(text(),'+')]",
'Childs_Remove_Button':"//div[contains(@class,'col 01')]//button[contains(@class,'btn btn-white bootstrap-touchspin-down')][contains(text(),'-')]",
'Hotels_Search_Button':"//div[contains(@class,'col-md-2 col-xs-12 o1')]//button[contains(@class,'btn btn-primary btn-block')][contains(text(),'Search')]",
'Flights_Link':"//a[contains(@class,'text-center flights')]",
'One_Way_Radio_Button':"//label[contains(text(),'One Way')]",
'Round_Trip_Button':"//label[contains(text(),'Round Trip')]",
'Dropdown_Economy':"//span[contains(text(),'Economy')]",
'Tours_Link':"//a[contains(@class,'text-center tours')]",
'Transfer_Link':"//a[contains(@class,'text-center transfer')]",
'Visa_Link':"//a[contains(@class,'text-center transfer')]",
'FirstName_Text':"//input[@placeholder='First Name']",
'LastName_Text':"//input[@placeholder='Last Name']",
'Mobile_Number_Text':"//input[@placeholder='Mobile Number']",
'Email_Text':"//input[@placeholder='Email']",
'Password_Text':"//input[@placeholder='Password']",
'Confirm_Password_Text':"//input[@placeholder='Confirm Password']",
'Got_It_Label_Button':"//button[@class='cc-btn cc-dismiss']",
'Sign_Up_Button':"//button[@class='signupbtn btn_full btn btn-success btn-block btn-lg']",
'User_Dropdown_Account_Page':"//div[@class='dropdown dropdown-login dropdown-tab']//a[@id='dropdownCurrency']",
'Account_Link':"//a[@class='dropdown-item active tr']",
'Logout_Link':"//a[@class='dropdown-item tr']",
'Bookings_Tab_Account_Page':"//a[contains(text(),'Bookings')]",
'My_Profile_Tab_Account_Page':"//a[contains(text(),'My Profile')]",
'Whishlist_Tab_Account_Page':"//a[contains(text(),'Wishlist')]",
'News_Letter_Tab_Account_Page':"//a[@class='go-text-right nav-link active']",
'NewsLetter_Subscribe_Button':"//span[@class='slider round']",

'Login_Username_Text':"//input[@placeholder='Email']",
'Login_Password_Text':"//input[@placeholder='Password']",
'Login_RememeberMe_Checkbox':"//label[@class='custom-control-label']",
'Login_page_Login_Button':"//button[@class='btn btn-primary btn-lg btn-block loginbtn']",
'Login_page_Sign_Up_Button':"//a[@class='btn btn-success br25 btn-block form-group']",
'Login_page_ForgetPassword_Button':"//a[@class='btn btn-warning br25 btn-block']",
'Forget_Password_Email_Text':"//input[@id='resetemail']",
'Forget_Password_Reset_Button':"//button[@class='btn btn-primary resetbtn']"

    
}