#-*- coding: utf-8 -*-
OR={
'Application_url': "http://vobes-ng01.david-bs.de:9081/vobesng/#/login",
'Firstpage_Arbeiten_click': "//button[@class='btn btn-primary ng-binding ng-scope'][contains(text(),'Arbeiten')]",
'Modulepage_Project_click': "//button[@class='btn btn-primary ng-binding ng-scope'][contains(text(),'Projekt')]",
'Homepage_Masterdata_Management_click': "//li[@ng-repeat='menuItem in menuList'][contains(text(),'Stammdatenverwaltung')]",
'project_menu': "xpath=//li[@ng-repeat='menuItem in menuList'][contains(text(),'Projekt')]",
'Masterdata_management_page_verify': "xpath=//li[@class='ng-binding'][contains(text(),'e42 Stammdaten')]",
'Homepage_createproject_click': "xpath=//span[contains(text(),'Fahrzeugprojekt anlegen')]",
'Create_project_input_project_name': "xpath=//input[@list='platforms']",
'Create_project_input_projectname_two': "xpath=//input[@list='subPlatforms']",
'Create_project_input_project_number': "xpath=//input[@list='projectNumbers']",
'Create_project_input_TMA': "xpath=//input[@list='TMAs']",
'Create_project_select_client': "//ul[@class='chosen-choices']",
'Create_project_select_clientname': "xpath=//li[contains(text(),'Audi')]",
'Home_menu': "//a[@ng-switch-when='false']",
'Home_search_field': "//input[@placeholder='Suchen']",
'Home_project_name': "xpath=//span[text()[contains(.,\"${ProjectName}\")]]",
'Home_existing_project_name': "xpath=//span[text()[contains(.,\"${Existing_Project}\")]]",
'Create_project_Save_button': "xpath=//button[@class='btn btn-primary ng-binding']",
'k2.0_application_url': "http://vobes-ng03.david-bs.de:9080/vobescons/app/#/tickets",
'dropdown_change_process': "//cons-change-construction-filter-toolbar[@class='p-2']//nz-select[2]//div",
'dropdown_input_field': "xpath=//cons-change-construction-filter-toolbar[@class='p-2']//nz-select[2]//div[1]//div//ul//li//input",
'Check_box_to_view_only_changes': "xpath=//label[@class='ant-checkbox-wrapper ng-untouched ng-pristine ng-valid']",
'WIRE_list_view': "xpath=//div[@class='ag-body-viewport ag-layout-normal ag-row-no-animation']",
'Extended_button': "xpath=//div[@class='ag-center-cols-container']//div[1]//div[17]//span[1]//button[1]",
'Pop_up_with_additional_details': "xpath=//div[@class='card dialog shadow ng-draggable ng-resizable ng-star-inserted']",
'Different_element_to_close_popup': "xpath=//div[@class='ag-row ag-row-no-focus ag-row-even ag-row-level-1 ag-row-position-absolute ag-row-hover']//div[@class='ag-cell ag-cell-not-inline-editing ag-cell-with-height ag-cell-no-focus ag-cell-value ag-column-hover']",
'Different_line_to_close_the_popup': "xpath=//div[@class='ag-cell ag-cell-not-inline-editing ag-cell-with-height ag-cell-value ag-cell-focus']",
'Button_to_view_graph': "//cons-viewer-sync-button[4]//div[1]//button[1]",
'Modified_element_one': "xpath=//div[@class='ag-center-cols-container']//div[1]//div[1]",
'Modified_element_two': "xpath=//div[@class='ag-center-cols-clipper']//div[7]//div[1]",
'Contact_column_value': "xpath=//div[@class='ag-center-cols-clipper']//div[3]//div[4]",
'Line_value': "xpath=//div[5]//div[11]",
'line_number_value': "xpath=//div[@class='ag-pinned-left-cols-container']//div[1]//div[2]",
'Additional_Module_details': "xpath=//div[6]//div[17]//span[1]//button[1]",
'list_values': "//div[@class='ng-dropdown-panel-items scroll-host']//span",
'dropdown_value': "//span[contains(text(),'TAB_016_999_B')]",
'table_of_tickets': "//div[@class='ag-center-cols-container']",
'ticket_to_select': "//div[@class='ag-center-cols-container']/div[1]",
'': "//div[@class='ag-header ag-pivot-off']",
'VOBES_id': "//div[@class='ag-center-cols-container']//div[1]//div[1]//span[1]",
'Column_Contact': "//div[@class='ag-center-cols-container']//div[1]//div[4]//span[1]",
'Dichtung_details': "//div[@class='ag-center-cols-clipper']//div[10]//div[10]//span[1]",
'leitung_details': "//div[@class='ag-center-cols-container']//div[1]//div[11]//span[1]",
'Column_potential': "//div[@class='ag-center-cols-container']//div[1]//div[16]//span[1]",
'Column_modules': "//div[@class='ag-center-cols-clWIRE_list_tableipper']//div[1]//div[17]//span[1]",
'search_WIRE_list': "//input[@placeholder='Suchen']",
'Search_change_process': "//input[@placeholder='Suchen']",
'Button_with_no_function': "//button[@class='btn btn-light btn-sm text-nowrap']",
'table_of_tickets_space': "//div[@class='ag-root ag-unselectable ag-layout-normal']",
'Deatils_header': "//cons-ticket-details[@class='w-50 ml-3']",
'Tickets_details_body': "//div[@class='card-body']",
'open_change_process': "xpath=//button[@class='button-blue ml-2 ant-btn ant-btn-default ant-btn-sm']",
'open_change_process_button': "//button[@class='button-blue ml-2 ant-btn ant-btn-default ant-btn-sm']",
'plattforms_offnen': "//div[@id='innerpanelB']//ul[1]//li[1]//a[1]//span[contains(text(), 'Plattform')]",
'First_row_of_table': "//tbody//tr[1]",
'Datenstand_menu': "xpath=//body/div[@class='ng-scope']/div[@class='ng-scope']/div[@id='mainWrapper']/div[@id='innerMainPage']/div[@class='ng-scope']/aside[@id='workMenu']/div[@id='innerpanelB']/div[@class='ng-scope']/div/ul[1]/li[3]/a[1]",
'Datenstand_anlegen': "xpath=//a[contains(text(),'Anlegen')]",
'Statistik_von_E_komponenten': "xpath=//span[contains(text(),'Statistik von E-Komponenten')]",
'Statistik_von_E_komponenten_window': "xpath=//div[@class='col-md-7 col-sm-7 col-lg-7']",
'Select_permision_type': "//select[@class='form-control ng-pristine ng-untouched ng-valid ng-not-empty']",
'statistik_placeholder': "xpath=//input[@placeholder='KW/JJJJ']",
'Statistiks_Partnumber': "xpath=//input[@placeholder='Teilenummer1;Teilenummer2;...']",
'Statistik_confirm_download': "xpath=//button[@class='btn btn-primary ng-binding']",
'Plattfrom_tabletwo_controller': "xpath=//div[@var-controller='platformTableTwoController']//div//div[@class='row panel panel-info']//div[@class='panel-body']//div[@id='container']//table[@class='table']//tbody//tr",
'Bauteilliste_Gesamt_SYS': "//span[contains(text(),'Bauteilliste Gesamt-SYS erstellen')]",
'Pop_up': "xpath=//div[@class='modal-content']",
'Confirm_button': "xpath=//button[contains(text(),'Ja')]",
'Project_offnen': "//div[@class='ng-scope']/div/ul[1]/li[1]/a[1]//span[contains(text(), 'Projekt')]",
'Trennstellenliste_menu': "xpath=//span[@class='ng-binding'][contains(text(),'Trennstellenliste')]",
'Bearbeiten_option': "xpath=//a[@ng-if='!child.nghref'][contains(text(),'Bearbeiten')]",
'Separation_point_view': "xpath=//div[@id='separationPointView']",
'Save_button_in_seperation_view': "//div[@class='col-md-4 textCentered']//button[@type='button'][contains(text(),'Speichern')]",
'Successful_pop_up': "//div[@class='modal-content']",
'Ja_button': "//div[@class='modal-footer ng-scope']//button[@type='button'][contains(text(),'Ok')]",
'Master_data_window': "xpath=//li[contains(text(),'Stammdatenverwaltung')]",
'master_data_import_button': "xpath=//span[@class='ng-binding' and text()='e42 Import']",
'Ok_button': "xpath=//span[@class='btn btn-primary']",
'Confirm_upload': "xpath=//button[@id='confirmUpload']",
'Statistik_von_komponenten': "xpath=//span[contains(text(),'Statistik von Komponenten')]",
'BOM_report_option': "xpath=//span[contains(text(),'Bauteilliste (BOM) exportieren')]",
'BOM_report_pop_up': "xpath=//div[@class='modal-content']",
'BOM_report_confirm': "xpath=//button[contains(text(),'Ja')]",
'WIRElist_report_option': "xpath=//span[contains(text(),'Wirelist')]",
'WIRElist_report_popup': "xpath=//div[@class='modal-content']",
'WIRElist_report_confirm': "xpath=//button[contains(text(),'Ja')]",
'Vorzugsteile_report_option': "xpath=//span[contains(text(),'Vorzugsteile-Report')]",
'Vorzugsteile_validation_option': "xpath=//select[@class='chzn-select form-control ng-pristine ng-untouched ng-valid ng-empty']",
'Option_value': "xpath=//option[@value='{\"option\":\"E42_VERSION\",\"data\":\"7.9.98\",\"description\":\"Stammdaten Version <7.9.98>\"}']",
'Vorzugsteile_report_confirm_button': "xpath=//button[contains(text(),'Ok')]",
'JSON_value': "xpath=//html//body//pre",
'Text_area_in_converter_for_JSON': "xpath=//textarea[@id='txt1']",
'Convert_JSON_to_xml_button': "xpath=//input[@id='btnRun']",
'download_xml_file': "xpath=//input[@value='Download Result']",
'Slot_A': "xpath=/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[5]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/table[1]/tbody[1]/tr[1]/th[1]/div[1]/div[1]",
'Slot_A_one':"xpath=/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[5]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/table[1]/tbody[1]/tr[1]/th[1]/div[2]/div[1]",
'Slot_B': "/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[5]/div[1]/div[2]/div[1]/div[1]/div[1]/div[3]/table[1]/tbody[1]/tr[1]/th[3]/div[1]/div[1]",
'Slot_C': "/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[5]/div[1]/div[2]/div[1]/div[1]/div[1]/div[4]/table[1]/tbody[1]/tr[1]/th[1]/div[1]/div[1]",
'Slot_D': "/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[5]/div[1]/div[2]/div[1]/div[1]/div[1]/div[5]/table[1]/tbody[1]/tr[1]/th[1]/div[1]",
'Datenstand_input_project_name': "xpath=//input[@id='name']",
'Datenstand_input_weekandYear': 'xpath=//input[@id=\"weekAndYear\"]',
'Datenstand_radio_button': "xpath=//div[@id='inputArea']/label[5]/input",
'Datenstand_save_button': "xpath=//button[@class='btn btn-default ng-binding'][contains(text(),'Speichern')]",
'Datenstand_tab_sucess_alert': "xpath=//div[@class='modal-header alert-success']",
'Datenstand_tab_sucess_alert_ok_button': "//button[@class='btn btn-primary ng-binding']",
'Datenstand_tab_record': "xpath=//div[@id='container']/table/tbody/tr",
'SYS_Datenstand_menu': "xpath=//span[@class='ng-binding'][contains(text(),'SYS-Datenstand anlegen')]",
'SYS_Datenstand_input_baseline': "xpath=//input[@name='vehPlatformBaseline']",
'SYS_Datenstand_radio_button': "xpath=//div[@id='innerMainPage']/div/div/div/div/div[1]/div/div[1]/label[1]/input",
'SYS_Datenstand_Save_button': "xpath=//button[@class='btn btn-primary ng-binding']",
'SYS_Datenstand_popup': "xpath=//h4[@class='modal-title ng-binding']",
'SYS_Datenstand_popup_ok_button': "xpath=//button[@type='button'][contains(text(),'OK')]",
'SYS_Datenstand_record': "xpath=//div[@id='innerMainPage']/div/div/div/div/div[2]/select/option[2]",
'SYS_import_menu': "xpath=//span[@class='ng-binding'][contains(text(),'Systemschaltplan importieren')]",
'SYS_import_upload_button': "xpath=//span[@class='btn btn-primary']",
'SYS_import_vehiclebaseline': "xpath=//select[@id='vehicleplatschembaseline']",
'SYS_import_choose_masterdata': "xpath=//a[@class='chosen-single chosen-default']//div//b",
'SYS_import_masterdatabse_value': "xpath=//li[text()[contains(.,\"08:40 04-04-2019 - 7.9.98 - undefined\")]]",
'SYS_import_Button': "xpath=//button[@id='confirmUpload']",
'SYS_import_confirmation_popup': "xpath=//div[@class='modal-header alert-primary']",
'SYS_import_confirmation_button': "xpath=//button[@class='btn btn-primary ng-binding'][contains(text(),'Ja')]",
'SYS_import_confirmation_msg': "xpath=//div[text()[contains(.,\"Der SYS Import wurde erfolgreich ausgeführt\")]]",
'Info_menu': "xpath=//ul[@id='topLevel']//li[@class='ng-binding ng-scope'][contains(text(),'Info')]",
'import_info_option': "xpath=//ul[@id='secondLevel']//li[1]",
'SYS_import_status': "xpath=//tbody//tr[1]",
'Datenstand': "xpath=//span[text()=\"Datenstand\"]",
'Zuweisen_SYS_Datenstand': "xpath=//a[@ng-if='!child.nghref'][contains(text(),'Zuweisen SYS-Datenstand')]",
'Select_project_SYS_Datenstand': "xpath=//select[@class='form-control ng-pristine ng-untouched ng-valid ng-empty']",
'Save_button_Zuweisen_SYS_Datenstand': "xpath=//button[@class='btn btn-primary ng-binding']",
'Zuweisen_SYS_Datenstand_popup': "xpath=//div[@class='modal-content']",
'Zuweisen_SYS_Datenstand_popup_confirmation': "xpath=//button[@type='button'][contains(text(),'OK')]",
'Project_menu_navigationbar': "xpath=//a[@ng-switch-when='false'][contains(text(),'Projekt')]",
'Masterdatabase_Datenstand_zuweisen': "xpath=//span[@class='ng-binding'][contains(text(),'e42 Datenstand zuweisen')]",
'Row_with_masterdata_version': "xpath=//tr[@st-select-row='row']",
'Assign_button_masterdata': "xpath=//button[@id='confirmUpload']",
'Masterdata_assignment_popup': "xpath=//div[@class='modal-dialog modal-lg']",
'Masterdata_assignment_confirmation': "xpath=//button[@class='btn btn-primary ng-binding'][contains(text(),'Ok')]",
'Plattform_menu_navigator': "xpath=//a[@ng-switch-when='false'][contains(text(),'Plattform')]",
'Second_row_ofthe_table': "xpath=//div[@var-controller='platformTableTwoController']//div//div[@class='row panel panel-info']//div[@class='panel-body']//div[@id='container']//table[@class='table']//tbody//tr",
'Gesamt_SYS_Datenstand': "xpath=//span[contains(text(),'Gesamt-SYS-Datenstand abschliessen')]",
'Gesamt_SYS_Datenstand_popup': "xpath=//div[@class='modal-content']",
'Gesamt_SYS_Datenstand_popup_confirm_button': "xpath=//button[@class='btn btn-primary ng-binding']",
'Kbl_import_menu': "xpath=//span[@class='ng-binding'][contains(text(),'KBL')]",
'Import_info_status_dropdown': "//th[9]//select[1]",
'Export_info_menu': "xpath=//span[contains(text(),'Export - Info')]", 
'Export_info_row_one': "//th[6]//select[1]",
'Export_tab': "xpath=//span[@class='ng-binding'][contains(text(),'Export')]",
'Export_option': "xpath=//a[@ng-if='!child.nghref'][contains(text(),'Bordnetz-VEC')]",
'Export_window_dropdown': "xpath=//a[@class='chosen-single chosen-default']//div//b",
'Export_window_masterdatabse_option': "xpath=//li[text()[contains(.,\"E42-Version des ausgewählten Fahrzeug-Projekts: 08:40 04-04-2019 - 7.9.98\")]]",
'Export_window_checkbox': "xpath=//input[@type='checkbox']",
'download_vec_button': "xpath=//a[@class='btn btn-primary ng-binding']",
'session_timeout_popup': "xpath=//div[contains(@class,'modal-dialog')]",
'Session_timeout_value': "xpath=/html[1]/body[1]/div[1]/div[1]/div[1]",
'Session_timeout_button': "xpath=/html[1]/body[1]/div[1]/div[1]/div[1]/div[3]/center[1]/button[1]",
'Calculate_distance_option': "xpath=//a[contains(text(),'Umstecken auf Steckplatz')]",
'Calculate_distance_popup': "xpath=//div[@class='modal-dialog modal-lg']//div[@class='modal-content trennstelleModals']",
'Calculate_distance_value': "xpath=//option[contains(text(),'')][1]",
'Calculate_distance_button': "xpath=//button[@class='btn btn-success ng-scope']",
'Delete_project_popup': "xpath=//div[@class='modal-content']",
'Delete_project_popup_ok': "xpath=//button[contains(text(),'Ja')]",
'Delete_project_success_alert': "xpath=//div[@class='modal-header alert-success']",
'Delete_project_button': "xpath=//button[@type='button']",
'Delete_project_warning_alert': "xpath=//div[@class='modal-header alert-warning']",
'Delete_project_negative_row': "xpath=//tr[@class='ng-scope ng-isolate-scope st-selected']",
'Separate_point_view_heading_menu': "xpath=//div[@class=\"alert-primary\"]//h3[@class=\"panel-title ng-binding\"]",
'Distance_calculation_option': "xpath=//a[@class='list-group-item context-menu-item'][contains(text(),'Trennstelle')]",
'Distance_calculation_value': "xpath=//div[@class='modal-dialog modal-lg']//div[@class='modal-content trennstelleModals']",
'Distance_calculation_button': "xpath=//button[@class='btn btn-success ng-scope']",
'KBL_tab': "xpath=//span[@class='ng-binding'][contains(text(),'KBL')]",
'kbl_import_option': "xpath=//span[text()=\"KBL\"]/parent::a/following-sibling::ul/li[1]/a",
'kbl_import_masterdatabase': "xpath= //li[contains(text(),'08:40 04-04-2019 - 7.9.98')]",
'import_option_kbl': "xpath=//label[@for='files']",
'confirm_upload': "xpath=//button[@id='confirmUpload']",
'confirm_upload_button': "xpath=//button[@class='btn btn-default ng-binding'][contains(text(),'Ok')]",
'IMport_status': "xpath=//div[@class='ng-scope']/a",
'refresh_button': "xpath=//button[@class='btn btn-sm btn-outline-light ml-auto']",
'Fahrzeugdatenstand_tab': "xpath=//a[@ng-switch-when='false'][contains(text(),'Fahrzeugdatenstand')]",
'Fahrzeugdatenstand_row': "xpath=//table[@class='table']//tbody",
'separate_window_pre_condition': "//span[contains(text(), \"Trennstellen übernehmen\")]",
'WIRE_list_line_number': "xpath=//div[@class='ag-pinned-left-cols-container']//div[1]//div[2]",
'WIRE_list_von_vobes_id': "xpath=//div[@class='ag-center-cols-container']//div[1]//div[1]//span[1]",
'WIRE_list_von_kurzname': "xpath=//div[@class='ag-center-cols-container']//div[1]//div[2]",
'WIRE_list_von_pin': "xpath=//div[@class='ag-center-cols-container']//div[1]//div[3]",
'WIRE_list_von_kontakt': "xpath=//div[@class='ag-center-cols-container']//div[2]//div[4]",
'WIRE_list_von_Dichtung': "xpath=//body//div[5]//div[5]",
'WIRE_list_nach_vobes_id': "xpath=//div[@class='ag-center-cols-container']//div[2]//div[6]//span[1]",
'WIRE_list_nach_kurzname': "xpath=//div[@class='ag-center-cols-container']//div[2]//div[7]//span[1]",
'WIRE_list_nach_pin': "xpath=//div[@class='ag-center-cols-container']//div[1]//div[8]",
'WIRE_list_nach_kontakt': "xpath=//div[@class='ag-center-cols-container']//div[2]//div[9]//span[1]",
'WIRE_list_nach_Dichtung': "xpath=//div[6]//div[10]",
'WIRE_list_leitung': "xpath=//div[@class='ag-center-cols-container']//div[1]//div[11]//span[1]",
'WIRE_list_sonderltg': "xpath=//div[@class='ag-center-cols-container']//div[1]//div[12]",
'WIRE_list_lanhe': "xpath=//div[@class='ag-center-cols-container']//div[1]//div[13]//span[1]",
'WIRE_list_farbe': "xpath=//div[@class='ag-center-cols-container']//div[1]//div[14]//span[1]",
'WIRE_list_querschn': "xpath=//div[@class='ag-center-cols-container']//div[1]//div[15]",
'WIRE_list_potential': "xpath=//div[@class='ag-center-cols-container']//div[1]//div[16]",
'WIRE_list_modularity': "xpath=//div[@class='ag-center-cols-container']//div[1]//div[17]//span[1]",
'konstruktion_wiringharnesses_button': "xpath=//button[@class='btn btn-sm shadow-none']",
'task_id_one': "xpath=//span[contains(text(),'AEM-00001')]",
'ELZ_viewer_refresh_button': "//button[@class='btn btn-sm btn-outline-light ml-auto']",
'Button_to_add_new_task': "//button//span[contains(text(), 'Änderungskonstruktion')]",
'Form_to_add_new_task': "//cons-modal[contains(@class,'shadow-lg rounded')]",
'New_task_title': "//input[@id='inputTitle']",
'New_task_costunit': "//input[@id='inputCostUnit']",
'New_task_creation_ok_button':"//button[contains(text(),'OK')]",
'Button_to_edit_task': "xpath=//div[@class='col-sm']//button[1]",
'New_task_status_open': "//span[contains(text(),'Offen')]",
'Home_icon': "//cons-side-bar-item[1]//div[1]//cons-side-bar-icon[1]//div[1]",
'Task_status_inprocessing': "//span[contains(text(),'In Bearbeitung')]",
'task_status_change_button': "xpath=//button[@class='ml-2 ant-btn ant-btn-default ant-btn-sm ng-star-inserted']",
'Task_status_Prüfung': "//span[contains(text(),'In Prüfung')]",
'Task_status_request_integration': "//button[@class='button-yellow ml-3 ant-btn ant-btn-default ant-btn-sm']",
'Task_status_approved': "//span[contains(text(),'Genehmigt')]",
'New_task_inputControlPointBOM': "//input[@id='inputControlPointBOM']",
'New_task_inputDescription': "//textarea[@id='inputDescription']",
'New_task_inputAssignee': "//input[@id='inputAssignee']",
'New_task_inputDeploymentDate': "//input[@id='inputDeploymentDate']",
'New_task_creation_button': "//button[contains(text(),'OK')]",
'Task_description_form': "//div[@class='content ng-star-inserted']",
'Task_edit_form': "//cons-modal[contains(@class,'shadow-lg rounded')]",
'Task_status_to_integrated': "//button[@class='button-green ml-3 ant-btn ant-btn-default ant-btn-sm']",
'Task_status_abort_integration': "//button[@class='button-red ml-2 ant-btn ant-btn-default ant-btn-sm']",
'Task_to_integrate': "//button[@class='button-grey ml-3 ant-btn ant-btn-default ant-btn-sm']",
'Rule_checking_icon': "//cons-side-bar-item[7]//div[1]//cons-side-bar-icon[1]//div[1]",
'Start_rule_check_button': "//body//button[2]",
'Dropdown_Rule_Set': "//div[@class='ant-select-selection__rendered']",
'Dropdown_Rule_Set_value': "//li[@class='ant-select-dropdown-menu-item ng-star-inserted']",
'Separation_points_Editor_icon': "//cons-side-bar-item[9]//div[1]//cons-side-bar-icon[1]//div[1]",
'Admin_icon': "//button[@class='ant-btn ant-dropdown-trigger ant-btn-primary']",
'Task_icon': "//cons-side-bar-item[2]//div[1]//cons-side-bar-icon[1]//div[1]",
'Overview_icon': "//cons-side-bar-item[3]//div[1]//cons-side-bar-icon[1]//div[1]",
'SYS_icon': "//cons-side-bar-item[3]//div[1]//cons-side-bar-icon[1]//div[1]",
'Wire_icon': "//cons-side-bar-item[4]//div[1]//cons-side-bar-icon[1]//div[1]",
'BOM_icon': "//cons-side-bar-item[5]//div[1]//cons-side-bar-icon[1]//div[1]",
'graphic_system': "//cons-side-bar-item[7]//div[1]//cons-side-bar-icon[1]//div[1]",
'AEM_preview': "//cons-side-bar-item[6]//div[1]//cons-side-bar-icon[1]//div[1]",
'Vehicle_project_overview_icon': "//cons-side-bar-item[10]//div[1]//cons-side-bar-icon[1]//div[1]",
'Added_suspended_lines': "//span[@class='btn-link']",
'suspende_row_added': "//div[@class='ag-center-cols-container']",
'Button_to_Create_PDFtestreport': "//button[@class='ant-btn ant-btn-primary ant-btn-sm']",
'Detail_review_header': "//div[@class='content-header p-4']",
'Task_edit_button': "//div[@class='col-sm']//button[1]",
'Delta_SYS_import_button': "//div[@class='w-50 pl-5 pr-5 details-content']//button[3]",
'CATIA_icon': "//span[contains(text(), ' CATIA ')]",
'Bvision_icon': "//span[contains(text(), ' B-Vision ')]",
'HarnessNavigator_icon': "//span[contains(text(), ' Harness Navigator ')]",
'ELZviewer_icon': "//cons-viewer-sync-button[4]//div[1]//button[1]",
'Table_of_content_task_one': "//span[contains(text(),'AEM-00000')]",
'empty_row_separation_point_editor': "//div[@class='ag-center-cols-clipper']",
'Task_id_two': "//span[contains(text(),'AEM-00001')]",
'Add_separation_point': "//span[contains(text(),'Trennstelle erstellen')]",
'existing_separation_point': "//span[contains(text(),'TAL ')]",
'Arrow_icon_home': "//span[@class='arrow-right']",
'Element_in_wireList': "//div[@class='ag-center-cols-container']//div[2]//div[3]//span[1]",
'Task_id_zero': "//span[contains(text(),'AEM-00000')]",
'Task_id_three': "//span[contains(text(),'AEM-00002')]",
'Pin_number_wireList': "//div[@class='ag-body-viewport ag-layout-normal ag-row-no-animation']//div[5]//div[3]",
'New_pin_value': "//div[contains(text(),'4')]",
'Task_id_four': "//span[contains(text(),'AEM-00003')]",
'Pin_number_two_in_wireList': "//div[@class='ag-body-viewport ag-layout-normal ag-row-no-animation']//div[6]//div[3]",
'Pin_number_three_in_wireList': "//div[@col-id='pinFrom']//span[contains(text(),'3')]",
'New_pin_number_two': "//div[contains(text(),'3')]",
'Last_row_with_YellowColorPin': "//div[@class='ag-row ag-row-no-focus ag-row-odd ag-row-level-1 ag-row-position-absolute ag-row-last']//span[@class='ag-icon ag-icon-checkbox-unchecked']",
'Dailog_to_create_separation_point': "//div[@class='ant-modal-content']",
'List_with_separation_points': "//div[@class='ng-select-container ng-has-value']",
'Input_field_for_separationPoint': "//div[@class='ng-select-container ng-has-value']//input",
'Button_to_create_separationPoint': "//button[@class='ant-btn ng-star-inserted ant-btn-default ant-btn-primary']",
'Separation_editor_save_button': "//button[@class='btn btn-sm btn-light']",
'Existing_separation_point_TDL': "//span[contains(text(),'TDL')]",
'Dailog_to_delete_separationPoint': "//div[@class='ant-modal-content']",
'OK_button_to_delete_separationPoint': "//button[@class='ant-btn ng-star-inserted ant-btn-primary']",
'Dailog_to_create_newSlot': "//div[@class='ant-modal-content']",
'List_of_slots': "//div[@class='ng-select-container']",
'first_slot_of_list': "//div[@class = 'ng-option ng-star-inserted'][1]",
'Ok_button_to_add_slot': "//button[@class='ant-btn ng-star-inserted ant-btn-default ant-btn-primary']",
'OK_button_to_addslot': "//button[@class='ant-btn ng-star-inserted ant-btn-default ant-btn-primary']",
'OK_button_to_addslot': "//button[@class='ant-btn ng-star-inserted ant-btn-default ant-btn-primary']",
'existing_slot': "//span[@class='ag-group-value'][contains(text(),'D')]",
'Dailog_to_delete_slot': "//div[@class='ant-modal-body ng-star-inserted']",
'COnfirm_button_to_deleteSlot': "//button[@class='ant-btn ng-star-inserted ant-btn-primary']",
'Button_to_download_pdf_inAEM': "//button[@class='ant-btn ant-btn-default']",
'Vehicle_project_dropdown': "//cons-change-construction-filter-toolbar[@class='p-2']//nz-select[1]//div",
'Project_name_one': "//li[contains(text(),'e3')][1]",
'Project_name_three': "//li[contains(text(),'e3-showcase-q2')]",
'Project_name_two': "//li[contains(text(),'dv16')]",
'Task_id_five': "//span[contains(text(),'AEM-00006')]",
'Task_id_Six': "//span[contains(text(),'AEM-00007')]",
'Delta_sys_import': "//button[@title='Delta Sys importieren']",
'Dailog_to_importSYSdelta': "//cons-modal[@class='shadow-lg rounded ng-star-inserted']",
'Delta_sys_importButton': "//button[@class='ant-btn ng-star-inserted ant-btn-default']",
'Delta_sys_import_confirmButton': "//button[@class='ant-btn ant-btn-primary']",
'DeltaSYSImport_updated_value_one': "//div[@class='ag-row ag-row-no-focus ag-row-even ag-row-level-1 ag-row-position-absolute ag-row-last']//div//span[text()= '0']",
'DeltaSYSImport_updated_value_two': "//div[5]//div[8]",
'DeltaSYSImport_updated_value_three': "//div[@class='ag-row ag-row-no-focus ag-row-even ag-row-level-1 ag-row-position-absolute ag-row-last']//div[16]",
'DeltaSYSImport_updated_value_four': "//div[5]//div[16]",
'Delete_slots_existingSlot': "//div[contains(text(), 'TAB_052_123')][1]",
'Delete_slot_RemoveSlot': "//div[@class='ag-menu-list']",
'Delete_slot_dailogBox': "//div[@class='ant-modal-body ng-star-inserted']",
'Delete_slot_confirmButton': "//button[@class='ant-btn ng-star-inserted ant-btn-primary']",
'AddConnector_existingSlot': "//span[@class='ag-group-value'][contains(text(),'A')]",
'DailogBox_ConnectorsList': "//div[@class='ant-modal-content']",
'AddConnectors_InputForPartnumber': "//body//div[@class='cdk-overlay-container']//div//div[5]//div[1]//div[1]//input[1]",
'ConnectorsList_FirstConnector': "//div[@class='ag-pinned-left-cols-container']//div//div//span//span[1]",
'AddConnector_Okbutton': "//div[@class='ant-modal-footer ng-star-inserted']//button[2]",
'ConnectorsList_firstConnector_tocheck': "//div[4]//div[1]//span[1]//span[1]//span[2]",
'ConnectorsList_SecondConnector_tocheck': "//div[5]//div[1]//span[1]//span[1]//span[2]",
'ConnectorsList_ThirdConnector_tocheck': "//div[6]//div[1]//span[1]//span[1]//span[2]",
'CouplingWith_dialog': "//div[@class='ant-modal-content']",
'CouplingWith_dialog_button': "//button[@class='ant-btn ng-star-inserted ant-btn-default ant-btn-primary']",
'CouplingWith_dialog_firstElement': "//div[@class='ag-header-container']//div[1]//div[1]//div[1]//input[1]",
'CouplingWith_dialog_secondElement': "//div[@class='ag-header-row']//div[2]//div[1]//div[1]//input[1]",
'CouplingWith_dialog_thirdElement': "//div[3]//div[1]//div[1]//input[1]",
'CouplingWith_dialog_forthElement': "//div[4]//div[1]//div[1]//input[1]",
'CouplingWith_dialog_fifthElement': "//body//div[@class='cdk-overlay-container']//div//div[5]//div[1]//div[1]//input[1]",
'CouplingWith_dialog_sixthElement': "//body//div[@class='cdk-overlay-container']//div//div[6]//div[1]//div[1]//input[1]",
'CouplingWith_dialog_SeventhElement': "//body//div[@class='cdk-overlay-container']//div//div[7]//div[1]//div[1]//input[1]",
'CouplingWith_dialog_eighthElement': "//body//div[@class='cdk-overlay-container']//div//div[8]//div[1]//div[1]//input[1]",
'CouplingWith_dialog_ninthElement': "//body//div[@class='cdk-overlay-container']//div//div[9]//div[1]//div[1]//input[1]",
'CouplingWith_dialog_connectorTwo': "//body//div[@class='ant-tabs-nav']//div//div[2]",
'CouplingWith_dialog_Connectorthree': "//body//div[@class='ant-tabs-nav']//div//div[3]",
'DetailedTestReport_suspendedValue': "//span[@class='btn-link']",
'DetailedTestReport_ReportWindow': "//body//nz-breadcrumb-item[3]",
'VOBESMigration_HOmepageTabOne': "//div[@class='split left']//div[@class='centered']//button",
'VOBESMigration_createUpdateproject_createprojectbutton': "//button//span[contains(text(), 'Projekt')]",
'VOBESMigration_createUpdateproject_createprojectdialog': "//div[@class='ui-dialog ui-widget ui-widget-content ui-corner-all ui-shadow ui-hidden-container ui-draggable']",
'VOBESMigration_createUpdateproject_createproject_abortButton': "//span[contains(text(),'Abbrechen')]",
'VOBESMigration_createUpdateproject_tablewithProjectDetails': "//div[@id='tableForm:projectTable']//table",
'VOBESMigration_createUpdateproject_tablewithLinestrands': "//div[@id='tableForm:j_id_15']//table",
'VOBESMigration_Homebutton': "//body//a[3]",
'VOBESMigration_HOmepage_tabtwo': "//div[@class='split right']//div[@class='centered']//button",
'CouplingWith_button': "//div[@class='ant-modal-footer ng-star-inserted']//button[3]",
'Materialselection_dialog_cancel_button': "//button[@class='ant-btn ng-star-inserted ant-btn-default']",
'Materialselection': "//div[@class='ag-menu-list']",
'Materialselection_dialog': "//div[@class='ant-modal-content']",
'Materialselection_rowone_wirelist': "//div[@class='ag-body-viewport ag-layout-normal ag-row-no-animation']//div[6]//div[2]//div[1]",
'Materialselection_rowtwo_wirelist': "//div[@class='ag-pinned-left-cols-container']//div[1]//div[2]//div[1]",
'Materialselection_rowthree_wirelist': "//div[@class='ag-pinned-left-cols-container']//div[2]//div[2]//div[1]",
'Materialselection_rowfour_wirelist': "//div[@class='ag-pinned-left-cols-container']//div[3]//div[2]//div[1]",
'Materialselection_dialog_Wirelist_uncheck': "//span[@class='ag-selection-checkbox']//span[@class='ag-icon ag-icon-checkbox-checked']",
'PinNumber_tochange_wirelist': "//div[@class='ag-center-cols-container']//div[@role='row' and contains(@class, 'ag-row-last')]//div[3]",
'RecomendedPinNumber': "//div[contains(@class,'recommended')]",
'HighlightWireInELZ_RowOnetoSelect': "//div[@class='ag-pinned-left-cols-container']//div[1]//div[2]//div[1]//span[1]//span[2]",
'HighlightWireInELZ_RowTwotoSelect': "//div[@class='ag-pinned-left-cols-container']//div[2]//div[2]//div[1]//span[1]//span[2]",
'HighlightWireInELZ_RowThreetoSelect': "//div[@class='ag-pinned-left-cols-container']//div[3]//div[2]//div[1]//span[1]//span[2]",
'HighlightWireInELZ_RowFourtoSelect': "//div[@class='ag-pinned-left-cols-container']//div[4]//div[2]//div[1]//span[1]//span[2]",
'HighlightWireInELZ_RowOnetoDselect': "//div[@class='ag-pinned-left-cols-container']//div[3]//div[2]//div[1]//span[1]//span[1]",
'HighlightWireInELZ_RowTwotoDselect': "//div[@class='ag-pinned-left-cols-container']//div[4]//div[2]//div[1]//span[1]//span[1]",
'ConnectorWizard_RowvalueToOpenConnectorWizard': "//div//span[contains(text(),'XA.E15.1')]",
'ConnectorWizard': "//div[@class='ag-menu-list']",
'ConnectorWizard_dialog': "//div[@class='ant-modal-body ng-star-inserted']",
'ConnectorWizard_dialog_NewConnectorValue': "//div[@class='ag-cell ag-cell-not-inline-editing ag-cell-with-height']//span[@class='ag-selection-checkbox']//span[@class='ag-icon ag-icon-checkbox-unchecked']",
'ConnectorWizard_dialog_Savebutton': "//button[@class='ant-btn ng-star-inserted ant-btn-default ant-btn-primary']",
'ConnectorWizard_dialog_cancelBtn': "//button[@class='ant-modal-close ng-star-inserted']",
'Materialselection_dialog_arrowone': "//div[contains(text(),'Leitungsinformation')]//i",
'ConnectorWizard_taskList_NewTaskRow': "//div[@class='ag-center-cols-container']",
'Materialselection_dialog_arrowTwo': "//div[contains(text(),'Stromwerte')]//i",
'Materialselection_dialog_arrowThree': "//div[contains(text(),'Drahtquerschnittsbegrenzungen')]//i",
'Materialselection_dialog_tabOne': "//div[contains(text(),'Neue Sonderleitungen')]",
'Materialselection_dialog_tabTwo': "//div[contains(text(),'Vorhandene Sonderleitungen')]",
'Materialselection_dialog_tabThree': "//div[contains(text(), 'Einzelleitungen')]",
'Materialselection_dialog_searchField': "//input[@placeholder='Suchen *']",
'Materialselection_dialog_label': "//span[contains(text(),'FLR bevorzugen')]",
'Materialselection_dialog_checkBox': "//span[@class='ant-checkbox']",
'Materialselection_dialog_element': "//div[@class='ag-side-button']//button//div//span",
'Materialselection_dialog_Listofcolumns': "//div[@class='ag-tool-panel-wrapper']",
'Materialselection_dialog_filter': "//input[@placeholder='Filter...']",
'Materialselection_dialog_hideClmOne': "//div[@class='ag-side-bar ag-unselectable']//div[3]//div[1]//div[1]//div[1]//span[1]",
'Materialselection_dialog_hideClmTwo': "//div[@class='ag-side-bar ag-unselectable']//div[4]//div[1]//div[1]//div[1]//span[1]",
'Materialselection_dialog_hideClmThree': "//div[@class='ag-side-bar ag-unselectable']//div[6]//div[1]//div[1]//div[1]//span[1]",
'Materialselection_dialog_newCable': "//div[@class='ag-center-cols-clipper']//div[4]//div[1]//div[1]",
'Materialselection_dialog_ConfirmButton': "//button[@class='ant-btn ng-star-inserted ant-btn-default ant-btn-primary']",
'Materialselection_dialog_newcable_multipleWires': "//div[@class='ag-center-cols-clipper']//div[2]//div[1]//div[1]",
'ContactPartDetermination': "//div[@class='ag-menu-list']",
'ContactPartDetermination_dialog': "//div[@class='ant-modal-content']",
'ContactPartDetermination_dialog_cancelBtn': "//button[@class='ant-modal-close ng-star-inserted']",
'ContactPartDetermination_dialog_clmnvalue': "//div[@class='grid-connectors-selection']//div[@class='ag-center-cols-clipper']//div[3]",
'ContactPartDetermination_dialog_kontakt_value': "//div[@class='ag-center-cols-container']//div[contains(@class,'ag-row-selected')]//div[4]",
'ContactPartDetermination_dialog_ManualContact': "//div[@class='ag-menu-list']",
'Manual_contact_dialog': "//div[@class='ant-modal-content']",
'Manual_contact_dialog_dropdownoptn': "//div[@class='footer-selectbox']",
'Manual_contact_dialog_dropdown_value': "//li[@class='ant-select-dropdown-menu-item ng-star-inserted'][2]",
'Manual_contact_dialog_saveBtn': "//div[@dir = 'ltr'][2]//nz-modal//div//div[@class='ant-modal-content']//button[@class='ant-btn ant-btn-primary']",
'Manual_contact_dialog_cancelBtn': "//div[@dir = 'ltr'][2]//nz-modal//div//div[@class='ant-modal-content']//button[@class='ant-btn ant-btn-default']",
'ContactPartDetermination_dialog_saveBtn': "//button[@class='ant-btn ant-btn-primary']",
'Task_list_OpenInCATIA_btn': "//div[@class='ag-center-cols-clipper']//div[4]//span//button",
'WireList_MaterialSelectionWizard_attribute': "//span[contains(text(),'N_037_023_3')][1]",
'WireList_MaterialSelectionWizard_attribute_multiplerows': "//div[@class='ag-cell ag-cell-not-inline-editing ag-cell-with-height ag-cell-value ag-cell-focus']",
'WireList_MaterialSelectionWizard_attribute_two': "//div[@class='ag-center-cols-container']//div[5]//div[12]",
'WireList_MaterialSelection_updatedValueOne': "//div[@class='ag-center-cols-container']//div[contains(@class,'ag-row-last')]//div[11]",
'WireList_MaterialSelection_updatedValueTwo': "//div[@class='ag-center-cols-container']//div[contains(@class,'ag-row-last')]//div[13]",
'WireList_MaterialSelection_updatedValueThree': "//div[@class='ag-center-cols-container']//div[contains(@class,'ag-row-last')]//div[14]",
'WireList_MaterialSelection_updatedValueFour': "//div[@class='ag-center-cols-container']//div[contains(@class,'ag-row-last')]//div[15]",
'Wirelist_invalidConnector': "//div[@class='ag-center-cols-container']//div//div[contains(@class,'connector-invalid')][1]",
'WireList_Harnesses_menu': "//div[contains(@class,'ag-row-first')]",
'ContactPartDetermination_dialog_highlightedValue': "//div[@class='grid-connectors-selection']//div[@class='ag-body-viewport ag-layout-normal ag-row-no-animation']//div//div//div[contains(@class, 'cell-value-empty')]",
'ContactPartDetermination_dialog_highlightedValueOne': "//div[@class='grid-connectors-selection']//div[@class='ag-body-viewport ag-layout-normal ag-row-no-animation']//div//div//div[contains(@class, 'cell-value-empty')][1]",
'ContactPartDetermination_dialog_NothighlightedValue': "//div[@class='ag-center-cols-container']//div[contains(@class,'ag-row-selected')][1]",
'ContactPartDetermination_dialog_extendedButton': "//button[@class='btn btn-sm btn-outline-primary lh-04'][contains(text(),'...')]",
'ContactPartDetermination_dialog_connector': "//div[@class='ag-center-cols-container']//div[contains(text(),'TAL.1A1')]",
'ContactPartDetermination_dialog_rowone': "//div[@class='grid-terminals-selection']//div[@class='ag-center-cols-container']//div[@role='row'][1]//div[4]",
'ContactPartDetermination_dialog_Rowtwo': "//div[@class='grid-terminals-selection']//div[@class='ag-center-cols-container']//div[@role='row'][4]//div[4]",
'Manual_contact_dialog_KontaktTable': "//div[@dir = 'ltr'][2]//nz-modal//div//div[@class='ant-modal-content']//div[contains(@class,'star-inserted')]/fieldset[1]",
'Manual_contact_dialog_DichtungTable': "//div[@dir = 'ltr'][2]//nz-modal//div//div[@class='ant-modal-content']//div[contains(@class,'star-inserted')]/fieldset[2]",
'Manual_contact_dialog_newValue_kontakt': "//cons-terminal-wizard-terminal-selection-terminals//div[@class='ag-root-wrapper-body ag-layout-normal']//div[2]//div[1]//span[1]//span[1]//span[2]",
'Manual_contact_dialog_newValue_kontakt_Dichtung': "//fieldset[@class='ng-star-inserted']//div[@class='ag-root-wrapper-body ag-layout-normal']//div[2]//div[1]//span[1]//span[1]//span[2]",
'Manual_contact_dialog_KontaktTable_inputField': "//div[@class='grid-terminal-selection']//cons-terminal-wizard-terminal-selection-terminals//div//input[@class='ant-input ant-input-sm ng-untouched ng-pristine ng-valid ng-star-inserted']",
'Manual_contact_dialog_KontaktTable_valueDeleteIcon': "//div[@class='grid-terminal-selection']//cons-terminal-wizard-terminal-selection-terminals//div//span[@class='ant-input-suffix ng-star-inserted']",
'Manual_contact_dialog_DichtungTable_inputField': "//div[@class='grid-terminal-selection']//cons-terminal-wizard-terminal-selection-seals//div//input[@class='ant-input ant-input-sm ng-untouched ng-pristine ng-valid ng-star-inserted']",
'Manual_contact_dialog_DichtungTable_valueDeleteIcon': "//div[@class='grid-terminal-selection']//cons-terminal-wizard-terminal-selection-seals//div//span[@class='ant-input-suffix ng-star-inserted']",
'ContactPartDetermination_dialog_deletedValuesRow': "//div[@class='grid-terminals-selection']//div[@class='ag-center-cols-container']//div[@role='row'][4]//div[contains(@class,'cell-value-empty')]",
'ContactPartDetermination_dialog_connectorWithNoValues': "//div[contains(text(),'128')]",
'Manual_contact_dialog_newValue': "//div[@class='cdk-overlay-container']//div[@class='ag-pinned-left-cols-container']//div[4]//span[@class='ag-selection-checkbox']",
'updatedvalue_BOM': "//div[@class='ag-cell ag-cell-not-inline-editing ag-cell-with-height ag-cell-no-focus row-changed ag-cell-value']",
'Line_number_ContextMenu': "//div[@class='ag-menu']",
'Cable_line_numberAssignment': "//div[@class='ag-menu-list']//div[1]",
'Cable_line_numberAssignment_dialog': "//div[@class='ant-modal-content']",
'Cable_line_numberAssignment_dialog_modelFamilyCode_attribute': "//div[@class='ant-modal-content']//nz-select[1]",
'Cable_line_numberAssignment_dialog_Indexdropdown': "//div[@class='ant-modal-content']//nz-select[2]",
'Cable_line_numberAssignment_dialog_cancelbutton': "//div[@class='footer-container ng-star-inserted']//button[1]",
'Cable_line_numberAssignment_dialog_Savebutton': "//div[@class='footer-container ng-star-inserted']//button[2]",
'Cable_line_numberAssignment_dialog_arrowleftOne': "//div[@class='ag-paging-panel ag-unselectable']//button[1]",
'Cable_line_numberAssignment_dialog_arrowleftTwo': "//div[@class='ag-paging-panel ag-unselectable']//button[2]",
'Cable_line_numberAssignment_dialog_arrowrightOne': "//div[@class='ag-paging-panel ag-unselectable']//button[3]",
'Cable_line_numberAssignment_dialog_arrowrightTwo': "//div[@class='ag-paging-panel ag-unselectable']//button[4]",
'AEM_overview_exclamation': "//cons-side-bar-item[8]//div[1]//cons-side-bar-icon[1]//div//nz-badge/i",
'Rule_checking_Exclamation': "//cons-side-bar-item[9]//div[1]//cons-side-bar-icon[1]//div//nz-badge/i",
'Cable_line_numberAssignment_errormsg': "//div[@class='ant-notification-notice ant-notification-notice-closable ng-trigger ng-trigger-notificationMotion']",
'ChangeDesign_Window_Import_Delta_SYS_Icon':"//div[@class='col-sm']//button[2]",
'Import_SYS_popup_Title':"//cons-modal-title[contains(@class,'font-weight-bold')]",
'Import_SYS_popup_import_button':"//button[@class='ant-btn ng-star-inserted ant-btn-default']",
'Import_SYS_popup_OK_button':"//button[@class='ant-btn ant-btn-primary']",
'Wire_List_Modularity_Column_Name':"//div[contains(text(),'Modularität')]",
'Wire_List_Modularity_Menu':"//div[@class='ag-center-cols-clipper']//div[2]//div[1]//span[1]//button[1]",
'Wire_List_Modularity_Column_First_Value':"//div[@class='ag-center-cols-container']//div[1]//div[17]//span[1]",
'Wire_List_Modularity_Right_Click_Modularization_Menu':"//span[@class='ag-menu-option-text']",
'Wire_List_Only_Changes':"//span[@class='ant-checkbox']",
'Wire_List_Vobes_ID':"//div[@class='ag-center-cols-container']//div[1]//div[1]//span[1]",
'Wire_List_Connector_Wizard':"//span[@class='ag-menu-option-text']",
'Wire_List_Line_Number_First':"//span[contains(text(),'264006')]",
'Wire_List_Line_Number_Second':"//span[contains(text(),'264012')]",
'Wire_List_Line_Number_Assignment_Option':"//span[contains(text(),'Leitungsnummernvergabe')]",
'Line_Number_Assignment_Window_Title':"//div[contains(text(),'Leitungsnummernvergabe')]",
'Line_Number_Assignment_Window_Module_Family_Name':"//div[@class='ant-select-selection-selected-value ng-tns-c36-790 ng-star-inserted']",
'Line_Number_Assignment_New_Line_Number':"//ag-grid-angular[@class='ag-theme-balham ag-theme-block']//div[@class='ag-center-cols-container']//div[7]//div[3]",
'Line_Number_Assignment_Abort_button':"//button[@class='ant-btn ant-btn-default']",
'Line_Number_Assignment_Save_button':"//button[@class='ant-btn ant-btn-primary']",
'Line_Number_Assignment_Old_Line_Number_Update':"//ag-grid-angular[@class='ag-theme-balham ag-theme-block']//div[@class='ag-center-cols-container']//div[8]//div[1]",
'Connector_Wizard_Window_Title':"//h2[contains(text(),'Steckerassistent')]",
'Connector_Wizard_Window_Vobes_ID':"//span[@class='font-weight-bold'][contains(text(),'J505.1')]",
'Connector_Wizard_Window_Part_Number':"//span[@class='font-weight-bold'][contains(text(),'TAB_016_999_B')]",
'Connector_Wizard_New_Connector_Part_Number_Selection':"//span[contains(text(),'4E0_973_812_A')]",
'Connector_Wizard_Connector_Name':"//input[@id='shortId']",
'Connector_Wizard_Save_Button':"//button[@class='ant-btn ng-star-inserted ant-btn-default ant-btn-primary']",
'Connector_Wizard_Abort_Button':"//button[@class='ant-btn ng-star-inserted ant-btn-default']",
'Contact_Right_Click':"//div[18]//div[4]//span[1]",
'Contact_Right_Click_Select_contact_Option':"//span[@class='ag-menu-option-text']",
'Contact_Part_Identification_Window_Title':"//div[contains(text(),'Kontaktteileermittlung')]",
'Conatct_Parts_Identification_Automatic_Contact_Selection':"//button[@class='auto-terminal-selection-button ant-btn ant-btn-primary']",
'Conatct_Parts_Identification_Vobes_ID':"//div[contains(text(),'TAL.1A1')]",
'Conatct_Parts_Identification_Contact_Part_Number':"//div[@class='cdk-overlay-container']//div[@class='ag-center-cols-clipper']//div[2]//div[4]",
'Conatct_Parts_Identification_Right_Click_Contact_Part_Number_Option':"//span[@class='ag-menu-option-text']",
'Contact_Parts_Identification_Tooltip_checkbox':"//input[@class='ant-checkbox-input ng-valid ng-dirty ng-touched']",
'Conatct_Parts_Identification_Save_button':"//button[@class='ant-btn ant-btn-primary']",
'Conatct_Parts_Identification_Abort_button':"//button[@class='ant-btn ant-btn-default']",
'Manual_Contact_Selection_Window_Title':"//div[contains(text(),'Manuelle Kontaktauswahl')]",
'Manual_Contact_Selection_Vobes_ID_and_Shrotname':"//div[contains(text(),'TAL.1A1 (KS_1)')]",
'Manual_Contact_Selection_Existing_Contact':"//input[@class='ant-input ant-input-sm ng-pristine ng-valid ng-star-inserted ng-touched']",
'Manual_Contact_Selection_New_Contact_Value':"//span[contains(text(),'7L6_971_859_H')]",
'Manual_Contact_Selection_Save_button':"//div[@id='cdk-overlay-4']//nz-modal//div//button[@class='ant-btn ant-btn-primary']",
'Manual_Contact_Selection_Abort_button':"//div[@id='cdk-overlay-4']//nz-modal//div//button[@class='ant-btn ant-btn-default']",
'Modularization_PopUp_Title':"//h2[contains(text(),'Modularisierung')]",
'Modularization_PopUp_Radio_Button_Only_Assigned_Modules':"//label[@class='text-wrap ant-radio-wrapper']//input[@class='ant-radio-input']",
'Modularization_PopUp_Radio_Button_Only_Families_with_Assigned_Modules':"//label[@class='text-wrap ant-radio-wrapper']//input[@class='ant-radio-input']",
'Modularization_PopUp_Radio_Button_All':"//label[@class='text-wrap ant-radio-wrapper']//input[@class='ant-radio-input']",
'Modularization_PopUp_Module_Management_Button':"//button[@class='ant-btn ant-btn-primary']",
'Modularizatoin_PopUp_Automatic_Modularization_Button':"//button[@class='mt-2 ant-btn ng-star-inserted ant-btn-primary']",
'Modularization_PopUp_ModuleFamily_ModuleVariant_Text':"//cons-module-assignment-grid[@class='ng-star-inserted']//div[@class='ag-center-cols-container']//div[2]//div//span//span[4]",
'Modularization_PopUp_Close_Icon':"//button[@class='ant-modal-close close-button']",
'Fuse_Assembly_Table_Content':"//div[@class='ag-center-cols-viewport']",
'BOM_Menu_Icon':"//i[@class='fas fa-receipt']",
'BOM_page_SPLICE_Line_First':"//div[9]//div[5]//span[1]",
'BOM_page_SPLICE_Line_First_Shortname':"//span[contains(text(),'SP_TK')]",
'BOM_page_SPLICE_Line_First_VobesID':"//span[contains(text(),'YW001')]",
'BOM_page_SPLICE_Line_Second':"//div[11]//div[5]//span[1]",
'BOM_page_SPLICE_Line_Second_Shortname':"//span[contains(text(),'SP_ILH')]",
'BOM_page_SPLICE_Line_Second_VobesID':"//span[contains(text(),'R4')]",
'BOM_page_SPLICE_Line_Third':"//div[14]//div[5]//span[1]",
'BOM_page_SPLICE_Line_Third_Shortname':"//span[contains(text(),'SP_31')]",
'BOM_page_SPLICE_Line_Third_VobesID':"//span[contains(text(),'128')]",
'BOM_page_SPLICE_Line_Fourth':"//div[22]//div[5]//span[1]",
'BOM_page_SPLICE_Line_Fourth_Shortname':"//span[contains(text(),'SP_30AIL')]",
'BOM_page_SPLICE_Line_Fourth_VobesID':"//span[contains(text(),'Y1')]",
'BOM_Page_Modularity_Column':"//div[contains(text(),'Modularität')]",
'BOM_Page_Modularity_Column_First_Value':"//div[@class='ag-center-cols-container']//div[1]//div[9]//span[1]",
'BOM_Page_Modularization_Option':"//span[@class='ag-menu-option-text']",
'BOM_Modularization_New_Module_Family_Selection':"(//cons-module-assignment-grid[@class='ng-star-inserted']//div[@class='ag-center-cols-container']//div[5]//div[2]//span[1]//span[2])[2]",
'BOM_Modularization_Module_Management_Button':"//button[@class='ant-btn ant-btn-primary']",
'BOM_Modularization_Save_Button':"//button[@class='ml-2 ant-btn ant-btn-primary']",
'BOM_Modularization_Abort_Button':"//button[@class='ant-btn ant-btn-default']",
'BOM_Modularization_Tool_Tip_Message_Checkbox':"//input[@class='ant-checkbox-input ng-pristine ng-valid ng-touched']",
'Fuse_Menu_Icon':"//i[@class='fas fa-bolt']",
'Fuse_Page_MultiFuse_SI_Carrier':"(//div[@class='ag-center-cols-container']//div//div//span//span[2]/span[1])[2]",
'Fuse_Page_MultiFuse_SI_Group':"(//div[@class='ag-center-cols-container']//div//div//span//span[2]//span)[1]",
'Fuse_Page_MultiFuse_Relay_Group':"(//div[@class='ag-center-cols-container']//div//div//span//span[2]//span)[2]",
'Fuse_Page_MultiFuse_Relay_Slot_One':"(//div[@class='ag-center-cols-container']//div//div[2]//span//span[2]//span)[1]",
'Fuse_Page_MultiFuse_Relay_Slot_One_Expanded':"//div[@class='ag-cell ag-cell-not-inline-editing ag-cell-with-height ag-cell-value ag-cell-focus']//span[@class='ag-group-expanded']",
'Fuse_Page_MultiFuse_Relay_Slot_Two':"(//div[@class='ag-center-cols-container']//div//div[2]//span//span[2]//span)[2]",
'Fuse_Page_MultiFuse_Relay_Slot_Two_Expanded':"//div[@class='ag-cell ag-cell-not-inline-editing ag-cell-with-height ag-cell-value ag-cell-focus']//span[@class='ag-group-expanded']",
'Fuse_Page_MultiFuse_Relay_Slot_Line_Number':"//span[contains(text(),'11 1054/1051')]",
'Fuse_Page_MultiFuse_Relay_Slot_Relay_Equipment_Option':"//span[@class='ag-menu-option-text']",
'Fuse_Page_MultiFuse_Relay_Equipment_Title':"//h3[contains(text(),'Relais Bestückung')]",
'Fuse_Page_MultiFuse_Relay_Equipment_SI_Carrier_Part_Number_One':"//div[@class='ag-cell ag-cell-not-inline-editing ag-cell-with-height ag-cell-value ag-cell-focus']//span[@class='ag-selection-checkbox']",
'Sys_Only_Changes_Checkbox':"//label[contains(text(),'Nur Änderungen')]",
'Sys_Pin_Comment':"//div[@class='ag-center-cols-container']//div[1]//div[4]",
'Sys_Pin_Potential':"//div[@class='ag-center-cols-container']//div[3]//div[5]",
'Sys_Potential_Designation':"//div[@class='ag-center-cols-container']//div[3]//div[6]",
'Sys_Control_Criterion':"//div[@class='ag-center-cols-container']//div[3]//div[10]",
'Module_Management_ModuleFamily_second':"//cons-module-administration-grid//div[@class='ag-center-cols-container']//div[2]//div[1]//span[1]//span[2]//span[1]",
'Module_Management_Create_Module_Family_Button':"//button[@class='ant-btn button-blue-dark ant-btn-default ant-btn-circle ant-btn-sm']",
'Module_Management_VAR_Module_Family':"//cons-module-administration-grid//div[@class='ag-center-cols-container']//div[1]//div[1]//span[1]//span[4]",
'Module_Management_VAR_Module_Family_Expand':"//cons-module-administration-grid//div[@class='ag-center-cols-container']//div[1]//div[1]//span[1]//span[2]//span[1]",
'Create_Module_Families_Window_Title':"//h2[contains(text(),'Modulfamilien anlegen')]",
'Create_Module_Families_Save_Button':"//cons-add-module-families[@class='ng-star-inserted']//button[@class='ml-2 ant-btn ant-btn-primary']"
}